### ISSUE TITLE
Some Typos

### ISSUE THREAD

**Issue by randomshinichi** [coffeemug/coffeemug.github.com#3]
In 2016-01-25-betray.textile
'seize' should be 'cease
'Vulnerability' not 'Volnurability'

Love every single blog post BTW. Incredible insight. I wonder if I will be at your level 6 years from now too.

**Comment by coffeemug** [comment]
Thanks, fixed. Was hoping people wouldn't read `/drafts` (it doesn't show up in index), but no such luck :)
